import type { ResolvedStyle } from '../../src/types.ts';

/**
 * A fully populated `ResolvedStyle` for unit tests that build a styled tree by
 * hand. One copy: three drifted ones used to exist, and a new style property
 * had to be added to each of them.
 */
export function styleFixture(overrides: Partial<ResolvedStyle> = {}): ResolvedStyle {
  return {
    fontFamily: 'TestFont',
    fontSize: 16,
    fontWeight: 400,
    fontStyle: 'normal',
    fontVariantCaps: 'normal',
    color: 'black',
    textAlign: 'left',
    textTransform: 'none',
    textDecorationLine: 'none',
    textDecorationStyle: 'solid',
    textDecorationColor: 'black',
    textShadow: 'none',
    webkitTextStrokeWidth: 0,
    webkitTextStrokeColor: '',
    webkitTextFillColor: '',
    paintOrder: 'normal',
    webkitBackgroundClip: '',
    backgroundImage: 'none',
    letterSpacing: 0,
    wordSpacing: 0,
    fontKerning: 'auto',
    lineHeight: 20,
    verticalAlign: 'baseline',
    whiteSpace: 'normal',
    wordBreak: 'normal',
    overflowWrap: 'normal',
    unicodeBidi: 'normal',
    direction: 'ltr',
    display: 'block',
    width: 0,
    minWidth: null,
    minHeight: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    backgroundColor: 'transparent',
    borderTopWidth: 0,
    borderTopColor: 'transparent',
    borderTopStyle: 'none',
    borderRightWidth: 0,
    borderRightColor: 'transparent',
    borderRightStyle: 'none',
    borderBottomWidth: 0,
    borderBottomColor: 'transparent',
    borderBottomStyle: 'none',
    borderLeftWidth: 0,
    borderLeftColor: 'transparent',
    borderLeftStyle: 'none',
    flexDirection: 'row',
    gap: 0,
    flexGrow: 0,
    flexShrink: 1,
    flexBasis: null,
    listStyleType: 'disc',
    lineClamp: 0,
    textAlignLast: 'auto',
    textIndent: 0,
    ...overrides,
  }
}
